---

- name: Install dependencies
  apt: name='{{ item }}' update_cache=yes
  with_items: '{{ craft_pkgs + craft_extra_pkgs }}'

- name: Install tools
  get_url: url='{{ item.url }}' dest='{{ item.dest }}' mode='{{ item.mode| default('a+x') }}'
  with_items: '{{ craft_tools + craft_extra_tools }}'

- name: Ensure craft user exists
  user: name='{{ craft_user }}'

- name: Create craft directory
  file: state=directory path='{{ craft_path }}' owner='{{ craft_user }}' group='{{ craft_user }}' mode='775'
  when: craft_path| default(False)
  register: craft_path_register
  failed_when: craft_path_register.failed|default(False) and craft_path_register.group != 'dialout'

