---
- include_role: name=nbz4live.php-fpm private=true
  vars:
    php_fpm_version: 7.1
    php_fpm_apt_packages:
      - php7.1-fpm
      - php-mysql
      - php-mcrypt
      - php-mbstring
      - php-curl
      - php-gd
      - php-zip
      - zip
      - unzip
      - php-readline

    php_fpm_pools:
      - name: '{{ craft_fpm_pool_name }}'
        user: craft
        group: craft
        listen: 9001
        chdir: /
