---
- include_role: name=nbz4live.php-fpm private=true
  vars:
    php_fpm_version: 7.1
    php_fpm_apt_packages:
      - php7.1-fpm
      - php-mysql
      - php-mcrypt
      - php-mbstring
      - php-memcached
      - memcached
      - php-curl
      - php-gd
      - php-zip
      - zip
      - unzip
      - php-readline

    php_fpm_pools:
      - name: '{{ craft_fpm_pool_name }}'
        listen: '/var/run/fpm.{{ craft_fpm_pool_name }}.socket'
        user: '{{ craft_user }}'
        group: '{{ craft_user }}'
        listen.owner: www-data
        listen.group: www-data
        chdir: /
