---

- name: Set acl to allow ssh user to clone repo
  acl: path='{{ craft_path }}' entity='{{ ansible_user }}' default=yes etype=user permissions=rwx state=present
  when: craft_repo|default(False)

- name: Clone the git repo
  become: no
  git:
    accept_hostkey: yes
    repo: '{{ craft_repo }}'
    version: '{{ craft_repo_ref | default(omit) }}'
    update: '{{ craft_repo_update | default(False) }}'
    dest:  '{{ craft_path }}'
  register: craft_repo_status
  when: craft_path| default(False) and craft_repo| default(False)

- name: Set Craft directory permissions
  file: state=directory path='{{ craft_path }}' owner='{{ craft_user }}' group='{{ craft_user }}' recurse=yes
  when: craft_repo_status.changed

- name: Craft install
  shell: craft download -n -t -o
  become_user: '{{ craft_user }}'
  args:
    chdir: '{{ craft_path }}'
    creates: '{{ craft_path }}/craft/app/Craft.php'
  register: craft_install_status

- name: Craft install cleanup
  shell: 'git checkout -- {{ item }}'
  become_user: '{{ craft_user }}'
  args:
    chdir: '{{ craft_path }}'
  with_items:
    - craft/config/
    - craft/templates/
    - craft/plugins/
    - public/index.php
  when: craft_cleanup and craft_install_status.changed
