---

- name: Set acl to allow ssh user to clone repo
  acl: path='{{ craft_path }}' entity='{{ ansible_user }}' etype=user permissions=rwx state=present
  when: craft_repo|default(False)

- name: Clone the git repo
  become: no
  git:
    accept_hostkey: yes
    repo: "{{ craft_repo }}"
    version: "{{ craft_repo_ref | default(omit) }}"
    update: "{{ craft_repo_update | default('False') }}"
    dest:  "{{ craft_path }}"
  register: craft_repo_status
  when: craft_path|default(no) and craft_repo|default(no)

- name: Create craft directory
  file: state=directory path='{{ craft_path }}' owner='{{ craft_user }}' group='{{ craft_user }}' recurse="yes"
  when: craft_repo_status.changed

- name: Check if craft is installed
  stat: path='{{ craft_path }}/craft/app'
  become_user: '{{ craft_user }}'
  register: craft_app_status
  when: craft_path|default(False)
  changed_when: no

- name: Craft install
  shell: craft install -n -t -o
  become_user: '{{ craft_user }}'
  args:
    chdir: '{{ craft_path }}'
  failed_when: no
  register: craft_install_status
  when: not (craft_app_status.stat.isdir|default(False))

- name: Craft install cleanup
  shell: 'git checkout -- {{ item }}'
  become_user: '{{ craft_user }}'
  args:
    chdir: '{{ craft_path }}'
  with_items:
    - craft/config/
    - craft/templates/
    - craft/plugins/
    - craft/storage/*.*
    - craft/storage/.*
    - public/*.*
    - public/.*
  when: craft_install_status.changed
