---

- import_tasks: deps.yml

- import_tasks: fpm.yml
  when: craft_fpm_install

- import_tasks: install.yml

- import_tasks: mysql.yml
  when: craft_mysql_install

- import_tasks: nginx.yml
  when: craft_nginx_install
